function bettersim
close;

global l0_len l1_len l2_len l3_len l1_limit l2_limit l3_limit range

initialize
figsize = get(fig,'outerPosition');
% Create the GUI
% Add the panels
panel1 = uipanel('title', 'ForwardKinematics',... 
    'fontsize', 12,...
    'fontweight', 'bold',...
    'position', [0 0.32 figsize(3)/2 figsize(4)/1.35]);
    %'position', [0 0 .3 .5]);
    %'backgroundcolor', 'white',...
p1_size = get(panel1, 'Position');

panel2 = uipanel('title', 'InverseKinematics',... 
    'fontsize', 12,...
    'fontweight', 'bold',...
    'position',[0 0 figsize(3)/2 figsize(4)/2.5]);
    %'position',[0 0 .3 .5]);
    %'backgroundcolor', 'white',...

%% Fwd Kin Panel - Sliders
% Slider for Link1
slider1 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l1_limit(1),...
    'max', l1_limit(2),...
    'value', l1_len,...
    'position', [60 260 100 20],...
    'callback', @s1_button_press);
% Slider for Link2
slider2 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l2_limit(1),...
    'max', l2_limit(2),...
    'value', l2_len,...
    'position', [60 230 100 20],...
    'callback', @s1_button_press);
% Slider for Link4
slider3 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l1_limit(1),...
    'max', l1_limit(2),...
    'value', l1_len,...
    'position', [60 170 100 20],...
    'callback', @s1_button_press);
% Slider for Link5
slider4 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l2_limit(1),...
    'max', l2_limit(2),...
    'value', l2_len,...
    'position', [60 140 100 20],...
    'callback', @s1_button_press);
% Slider for Link7
slider5 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l2_limit(1),...
    'max', l2_limit(2),...
    'value', l2_len,...
    'position', [60 80 100 20],...
    'callback', @s1_button_press);
% Slider for Link8
slider6 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l2_limit(1),...
    'max', l2_limit(2),...
    'value', l2_len,...
    'position', [60 50 100 20],...
    'callback', @s1_button_press);
%% Fwd Kin Panel - Text
% Link1 min value
L1min = 1234;
text1 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', L1min,...
    'Position', [0 260 50 20]);
%     function s1_button_press(h,dummy)
%         slider_value = round(get(h,'Value'));
%         set(t1_edit,'string',slider_value);
%     end
% Link1 max value
text2 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L1 max',...
    'Position', [180 260 50 20]);
% Link2 min value
text3 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L2 min',...
    'Position', [0 230 50 20]);
% Link2max value
text4 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L2 max',...
    'Position', [180 230 50 20]);
% Link3 min value
text5 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L3 min',...
    'Position', [0 200 50 20]);
% Link3 max value
text6 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L3 max',...
    'Position', [180 200 50 20]);
% Link4 min value
text7 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L4 min',...
    'Position', [0 170 50 20]);
% Link4 max value
text8 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L4 max',...
    'Position', [180 170 50 20]);% Link3 min value
% Link5 min value
text9 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L5 min',...
    'Position', [0 140 50 20]);
% Link5 max value
text10 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L5 max',...
    'Position', [180 140 50 20]);
% Link6 min value
text11 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L6 min',...
    'Position', [0 110 50 20]);
% Link6 max value
text12 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L6 max',...
    'Position', [180 110 50 20]);
% Link7 min value
text13 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L7 min',...
    'Position', [0 80 50 20]);
% Link7 max value
text14 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L7 max',...
    'Position', [180 80 50 20]);
% Link8 min value
text15 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L8 min',...
    'Position', [0 50 50 20]);
% Link8 max value
text16 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L8 max',...
    'Position', [180 50 50 20]);
% Link9 min value
text17 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L9 min',...
    'Position', [0 20 50 20]);
% Link8 max value
text18 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L9 max',...
    'Position', [180 20 50 20]);
%% Fwd Kin Panel - Edit boxes
% L1 enditable field
edit1 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [220 260 30 20]);
% L2 enditable field
edit2 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [220 230 30 20]);
% L4 enditable field
edit3 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [220 170 30 20]);
% L5 enditable field
edit4 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [220 140 30 20]);
% L7 enditable field
edit5 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [220 80 30 20]);
% L8 enditable field
edit6 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [220 50 30 20]);
    function initialize
        l0_len = 1; l1_len = l0_len/cosd(30); l2_len = l1_len; l3_len = l1_len; 
        range = [2/3*l0_len/cosd(30), 4/3*l0_len/cosd(30)];
        l1_limit = range;   % Min and Max of the acctuators
        l2_limit = range;
        l3_limit = range;
        
        set(0,'Units','pixels');
        dim = get(groot,'ScreenSize');
        fig = figure('name','Parallel Manipulator',...
            'numbertitle','off',...
            'menubar','none',...
            'units','normalized',...%);
            'outerposition',[0.1 0.1 dim(3)/2000 dim(4)/1000]);
            %'position',[.1 .1 0.8 0.75]);
    end
end

