function sim501
close;

initialize

figsize = get(fig,'outerPosition')

% Create the GUI
%% Panels
panel1 = uipanel('title', 'Options',... 
    'units', 'pixels',...
    'fontsize', 12,...
    'fontweight', 'bold',...
    'position',[0 figsize(4)*.825 figsize(3)/3 figsize(4)*.12]);

panel2 = uipanel('title', 'ForwardKinematics',... 
    'units','pixels',...
    'fontsize', 12,...
    'fontweight', 'bold',...
    'position', [0 figsize(4)/4 figsize(3)/3 figsize(4)/1.75]);

panel3 = uipanel('title', 'InverseKinematics',... 
    'units', 'pixels',...
    'fontsize', 12,...
    'fontweight', 'bold',...
    'position',[0 0 figsize(3)/3 figsize(4)/4]);

% Get the dimensions of the panels
p1_size = get(panel1, 'Position')
p2_size = get(panel2, 'Position')
p3_size = get(panel3, 'Position')

%% Fwd Kin Panel - Sliders
% Slider for Link1
l1_slider = uicontrol('parent', panel2,...
    'style', 'slider',...
    'min', l11_limit(1),...
    'max', l11_limit(2),...
    'value', l11_len,...
    'position', [p2_size(3)*.275 p2_size(4)*.85 p2_size(3)/2.5 20],...
    'callback', @s1_button_press);

% Slider for Link2
l2_slider = uicontrol('parent', panel2,...
    'style', 'slider',...
    'min', l12_limit(1),...
    'max', l12_limit(2),...
    'value', l12_len,...
    'position', [p2_size(3)*.275 p2_size(4)*.75 p2_size(3)/2.5 20],...
    'callback', @s1_button_press);

% Slider for Link4 (l21)
l4_slider = uicontrol('parent', panel2,...
    'style', 'slider',...
    'min', l21_limit(1),...
    'max', l21_limit(2),...
    'value', l21_len,...
    'position', [p2_size(3)*.275 p2_size(4)*.55 p2_size(3)/2.5 20],...
    'callback', @s1_button_press);

% Slider for Link5 (l22)
l5_slider = uicontrol('parent', panel2,...
    'style', 'slider',...
    'min', l22_limit(1),...
    'max', l22_limit(2),...
    'value', l22_len,...
    'position', [p2_size(3)*.275 p2_size(4)*.45 p2_size(3)/2.5 20],...
    'callback', @s1_button_press);

% Slider for Link7 (l31)
l7_slider = uicontrol('parent', panel2,...
    'style', 'slider',...
    'min', l31_limit(1),...
    'max', l31_limit(2),...
    'value', l31_len,...
    'position', [p2_size(3)*.275 p2_size(4)*.25 p2_size(3)/2.5 20],...
    'callback', @s1_button_press);

% Slider for Link8 (l32)
l8_slider = uicontrol('parent', panel2,...
    'style', 'slider',...
    'min', l32_limit(1),...
    'max', l32_limit(2),...
    'value', l32_len,...
    'position', [p2_size(3)*.275 p2_size(4)*.15 p2_size(3)/2.5 20],...
    'callback', @s1_button_press);
%% Fwd Kin Panel - Text
% Link1 min value
L1min = 1234;
l1_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', L1min,...
    'Position', [p2_size(3)*.1 p2_size(4)*.84 50 20])

% Link1 max value
l1_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L1 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.84 50 20]);

% Link2 min value
l2_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L2 min',...
    'Position', [p2_size(3)*.1 p2_size(4)*.74 50 20]);

% Link2 max value
l2_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L2 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.74 50 20]);

% Link3 min value
l3_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L3 min',...
    'Position', [p2_size(3)*.1 p2_size(4)*.64 50 20]);

% Link3 max value
l3_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L3 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.64 50 20]);

% Link4 min value
l4_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L4 min',...
    'Position', [p2_size(3)*.1 p2_size(4)*.54 50 20]);

% Link4 max value
l4_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L4 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.54 50 20]);

% Link5 min value
l5_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L5 min',...
    'Position', [p2_size(3)*.1 p2_size(4)*.44 50 20]);

% Link5 max value
l5_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L5 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.44 50 20]);

% Link6 min value
l6_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L6 min',...
    'Position', [p2_size(3)*.1 p2_size(4)*.34 50 20]);

% Link6 max value
l6_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L6 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.34 50 20]);

% Link7 min value
l7_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L7 min',...
    'Position', [p2_size(3)*.1 p2_size(4)*.24 50 20]);

% Link7 max value
l7_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L7 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.24 50 20]);

% Link8 min value
l8_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L8 min',...
    'Position', [p2_size(3)*.1 p2_size(4)*.14 50 20]);

% Link8 max value
l8_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L8 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.14 50 20]);

% Link9 min value
l9_min = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L9 min',...
    'Position', [p2_size(3)*.1 p2_size(4)*.04 50 20]);

% Link9 max value
l9_max = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'L9 max',...
    'Position', [p2_size(3)*.7 p2_size(4)*.04 50 20]);

% Link labels
l1_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l1',...
    'Position', [0 p2_size(4)*.84 30 20]);

l2_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l2',...
    'Position', [0 p2_size(4)*.74 30 20]);

l3_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l3',...
    'Position', [0 p2_size(4)*.64 30 20]);

l4_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l4',...
    'Position', [0 p2_size(4)*.54 30 20]);

l5_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l5',...
    'Position', [0 p2_size(4)*.44 30 20]);

l6_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l6',...
    'Position', [0 p2_size(4)*.34 30 20]);

l7_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l7',...
    'Position', [0 p2_size(4)*.24 30 20]);

l8_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l8',...
    'Position', [0 p2_size(4)*.14 30 20]);

l9_label = uicontrol('parent', panel2,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l9',...
    'Position', [0 p2_size(4)*.04 30 20]);

%% Fwd Kin Panel - Edit boxes
% editable fields for the controled actuators
l1_edit = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.85 p2_size(4)*.85 35 20]);

l2_edit = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.85 p2_size(4)*.75 35 20]);

l4_edit = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.85 p2_size(4)*.55 35 20]);

l5_edit = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.85 p2_size(4)*.45 35 20]);

l7_edit = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.85 p2_size(4)*.25 35 20]);

l8_edit = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.85 p2_size(4)*.15 35 20]);

%% Inv Kin Panel - Text
% x, y, z position on golbal frame
x_pos = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'X:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p3_size(3)*.1 p3_size(4)*.5 30 20]);
 
y_pos = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'Y:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p3_size(3)*.4 p3_size(4)*.5 30 20]);

z_pos = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'Z:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p3_size(3)*.7 p3_size(4)*.5 30 20]);

% Direction (unit vector form)
xdir = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'X:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p3_size(3)*.1 p3_size(4)*.1 30 20]);
ydir = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'Y:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p3_size(3)*.4 p3_size(4)*.1 30 20]);
zdir = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'Z:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p3_size(3)*.7 p3_size(4)*.1 30 20]);

% Labels
ee_pos = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'EE pos',...
    'fontweight', 'bold',...
    'fontsize', 11,...
    'Position', [0 p3_size(4)*.7 100 20]);

ee_dir = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'EE dir (unit vector)',...
    'fontweight', 'bold',...
    'fontsize', 11,...
    'Position', [0 p3_size(4)*.3 125 20]);
%% Inv Kin Panel - Edit boxes
% X, Y, Z editable fields
x_edit = uicontrol('parent', panel3,...
    'style', 'edit',...
    'string', 0,...
    'position', [p3_size(3)*.2 p3_size(4)*.5 35 20]);

y_edit = uicontrol('parent', panel3,...
    'style', 'edit',...
    'string', 0,...
    'position', [p3_size(3)*.5 p3_size(4)*.5 35 20]);

z_edit = uicontrol('parent', panel3,...
    'style', 'edit',...
    'string', 0,...
    'position', [p3_size(3)*.8 p3_size(4)*.5 35 20]);

%direction
% X, Y, Z
xdir_edit = uicontrol('parent', panel3,...
    'style', 'edit',...
    'string', 0,...
    'position', [p3_size(3)*.2 p3_size(4)*.1 35 20]);

ydir_edit = uicontrol('parent', panel3,...
    'style', 'edit',...
    'string', 0,...
    'position', [p3_size(3)*.5 p3_size(4)*.1 35 20]);

zdir_edit = uicontrol('parent', panel3,...
    'style', 'edit',...
    'string', 0,...
    'position', [p3_size(3)*.8 p3_size(4)*.1 35 20]);
%% Graphical display
graph = axes('title', 'a graph',...
    'units','pixels',...
    'position', [figsize(3)*.4 figsize(4)*.1 figsize(4)*.75 figsize(4)*.75]);
    %'outerposition',[dim(3)*.125 dim(4)*.125 dim(3)*.75 dim(4)*.75]);
    
%% Options panel
l10_label = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'l10:',...
    'fontweight', 'bold',...
    'fontsize', 10,...
    'Position', [p1_size(3)*.01 p1_size(4)*.3 25 17]);

l20_label = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'l20:',...
    'fontweight', 'bold',...
    'fontsize', 10,...
    'Position', [p1_size(3)*.25 p1_size(4)*.3 25 17]);

l30_label = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'l30:',...
    'fontweight', 'bold',...
    'fontsize', 10,...
    'Position', [p1_size(3)*.49 p1_size(4)*.3 25 17]);

l10_edit = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 1,...
    'position', [p1_size(3)*.12 p1_size(4)*.3 25 17]);

l20_edit = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 1,...
    'position', [p1_size(3)*.37 p1_size(4)*.3 25 17]);

l30_edit = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 1,...
    'position', [p1_size(3)*.61 p1_size(4)*.3 25 17]);

pb1 = uicontrol('parent', panel1,...
    'style', 'pushbutton',...
    'fontweight', 'bold',...
    'fontsize', 10,...
    'string', 'Home',...
    'Position', [p1_size(3)*.75 p1_size(4)*.42 60 p1_size(4)*.3]);

pb2 = uicontrol('parent', panel1,...
    'style', 'pushbutton',...
    'fontweight', 'bold',...
    'fontsize', 10,...
    'string', 'Reset',...
    'Position', [p1_size(3)*.75 p1_size(4)*.1 60 p1_size(4)*.3]);
%% l0s

%% Other Stuff
    function initialize
        l10_len = 1; l11_len = l10_len/cosd(30); l12_len = l11_len; l13_len = l11_len; 
        range1 = [2/3*l10_len/cosd(30), 4/3*l10_len/cosd(30)];
        l11_limit = range1;   % Min and Max of the acctuators
        l12_limit = range1;
        l13_limit = range1;
        
        l20_len = 1; l21_len = l20_len/cosd(30); l22_len = l21_len; l23_len = l21_len; 
        range2 = [2/3*l20_len/cosd(30), 4/3*l20_len/cosd(30)];
        l21_limit = range2;   % Min and Max of the acctuators
        l22_limit = range2;
        l23_limit = range2;
        
        l30_len = 1; l31_len = l30_len/cosd(30); l32_len = l31_len; l33_len = l31_len; 
        range3 = [2/3*l30_len/cosd(30), 4/3*l30_len/cosd(30)];
        l31_limit = range3;   % Min and Max of the acctuators
        l32_limit = range3;
        l33_limit = range3;
        
        set(0,'Units','pixels');
        dim = get(groot,'ScreenSize')
        fig = figure('name','Parallel Manipulator',...
            'numbertitle','off',...
            'menubar','none',...
            'units','pixels',...%);
            'outerposition',[dim(3)*.125 dim(4)*.125 800 600]);
            %'outerposition',[dim(3)*.125 dim(4)*.125 dim(3)*.75 dim(4)*.75]);
            %'position',[.1 .1 0.8 0.75]);
    end
end

