function sim501
close;

global l0_len l1_len l2_len l3_len l1_limit l2_limit l3_limit range

initialize

figsize = get(fig,'outerPosition')
% Create the GUI
% Add the panels
panel1 = uipanel('title', 'ForwardKinematics',... 
    'units','pixels',...
    'fontsize', 12,...
    'fontweight', 'bold',...
    'position', [0 figsize(4)/4 figsize(3)/3 figsize(4)/1.75]);
    %'position', [0 0 .3 .5]);
    %'backgroundcolor', 'white',...

panel2 = uipanel('title', 'InverseKinematics',... 
    'units', 'pixels',...
    'fontsize', 12,...
    'fontweight', 'bold',...
    'position',[0 0 figsize(3)/3 figsize(4)/4]);
    %'position',[0 0 .3 .5]);
    %'backgroundcolor', 'white',...
    
panel3 = uipanel('title', 'Options',... 
    'units', 'pixels',...
    'fontsize', 12,...
    'fontweight', 'bold',...
    'position',[0 figsize(4)*.825 figsize(3)/3 figsize(4)*.12]);

p1_size = get(panel1, 'Position')
p2_size = get(panel2, 'Position')
p3_size = get(panel3, 'Position')
%% Fwd Kin Panel - Sliders
% Slider for Link1
slider1 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l1_limit(1),...
    'max', l1_limit(2),...
    'value', l1_len,...
    'position', [p1_size(3)*.275 p1_size(4)*.85 p1_size(3)/2.5 20],...
    'callback', @s1_button_press);
% Slider for Link2
slider2 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l2_limit(1),...
    'max', l2_limit(2),...
    'value', l2_len,...
    'position', [p1_size(3)*.275 p1_size(4)*.75 p1_size(3)/2.5 20],...
    'callback', @s1_button_press);
% Slider for Link4
slider3 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l1_limit(1),...
    'max', l1_limit(2),...
    'value', l1_len,...
    'position', [p1_size(3)*.275 p1_size(4)*.55 p1_size(3)/2.5 20],...
    'callback', @s1_button_press);
% Slider for Link5
slider4 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l2_limit(1),...
    'max', l2_limit(2),...
    'value', l2_len,...
    'position', [p1_size(3)*.275 p1_size(4)*.45 p1_size(3)/2.5 20],...
    'callback', @s1_button_press);
% Slider for Link7
slider5 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l2_limit(1),...
    'max', l2_limit(2),...
    'value', l2_len,...
    'position', [p1_size(3)*.275 p1_size(4)*.25 p1_size(3)/2.5 20],...
    'callback', @s1_button_press);
% Slider for Link8
slider6 = uicontrol('parent', panel1,...
    'style', 'slider',...
    'min', l2_limit(1),...
    'max', l2_limit(2),...
    'value', l2_len,...
    'position', [p1_size(3)*.275 p1_size(4)*.15 p1_size(3)/2.5 20],...
    'callback', @s1_button_press);
%% Fwd Kin Panel - Text
% Link1 min value
L1min = 1234;
text1 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', L1min,...
    'Position', [p1_size(3)*.1 p1_size(4)*.84 50 20])
%     'Position', [0 260 50 20]);
%     function s1_button_press(h,dummy)
%         slider_value = round(get(h,'Value'));
%         set(t1_edit,'string',slider_value);
%     end
% Link1 max value
text2 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L1 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.84 50 20]);
% Link2 min value
text3 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L2 min',...
    'Position', [p1_size(3)*.1 p1_size(4)*.74 50 20]);
% Link2max value
text4 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L2 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.74 50 20]);
% Link3 min value
text5 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L3 min',...
    'Position', [p1_size(3)*.1 p1_size(4)*.64 50 20]);
% Link3 max value
text6 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L3 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.64 50 20]);
% Link4 min value
text7 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L4 min',...
    'Position', [p1_size(3)*.1 p1_size(4)*.54 50 20]);
% Link4 max value
text8 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L4 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.54 50 20]);% Link3 min value
% Link5 min value
text9 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L5 min',...
    'Position', [p1_size(3)*.1 p1_size(4)*.44 50 20]);
% Link5 max value
text10 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L5 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.44 50 20]);
% Link6 min value
text11 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L6 min',...
    'Position', [p1_size(3)*.1 p1_size(4)*.34 50 20]);
% Link6 max value
text12 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L6 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.34 50 20]);
% Link7 min value
text13 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L7 min',...
    'Position', [p1_size(3)*.1 p1_size(4)*.24 50 20]);
% Link7 max value
text14 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L7 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.24 50 20]);
% Link8 min value
text15 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L8 min',...
    'Position', [p1_size(3)*.1 p1_size(4)*.14 50 20]);
% Link8 max value
text16 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L8 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.14 50 20]);
% Link9 min value
text17 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L9 min',...
    'Position', [p1_size(3)*.1 p1_size(4)*.04 50 20]);
    %'Position', [0 20 50 20]);
% Link9 max value
text18 = uicontrol('parent', panel1,...
    'style', 'text',...
    'string', 'L9 max',...
    'Position', [p1_size(3)*.7 p1_size(4)*.04 50 20]);
% Link1 label
text19 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l1',...
    'Position', [0 p1_size(4)*.84 30 20]);
% Link2 label
text20 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l2',...
    'Position', [0 p1_size(4)*.74 30 20]);
% Link3 label
text21 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l3',...
    'Position', [0 p1_size(4)*.64 30 20]);
% Link4 label
text22 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l4',...
    'Position', [0 p1_size(4)*.54 30 20]);
% Link5 label
text23 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l5',...
    'Position', [0 p1_size(4)*.44 30 20]);
% Link6 label
text24 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l6',...
    'Position', [0 p1_size(4)*.34 30 20]);
% Link7 label
text25 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l7',...
    'Position', [0 p1_size(4)*.24 30 20]);
% Link6 label
text26 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l8',...
    'Position', [0 p1_size(4)*.14 30 20]);
% Link6 label
text27 = uicontrol('parent', panel1,...
    'style', 'text',...
    'fontweight', 'bold',...
    'string', 'l9',...
    'Position', [0 p1_size(4)*.04 30 20]);

%% Fwd Kin Panel - Edit boxes
% L1 enditable field
edit1 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [p1_size(3)*.85 p1_size(4)*.85 35 20]);
% L2 enditable field
edit2 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [p1_size(3)*.85 p1_size(4)*.75 35 20]);
% L4 enditable field
edit3 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [p1_size(3)*.85 p1_size(4)*.55 35 20]);
% L5 enditable field
edit4 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [p1_size(3)*.85 p1_size(4)*.45 35 20]);
% L7 enditable field
edit5 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [p1_size(3)*.85 p1_size(4)*.25 35 20]);
% L8 enditable field
edit6 = uicontrol('parent', panel1,...
    'style', 'edit',...
    'string', 0,...
    'position', [p1_size(3)*.85 p1_size(4)*.15 35 20]);

%% Inv Kin Panel - Text
% x position 
text27 = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'X:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p2_size(3)*.1 p2_size(4)*.5 30 20]);
% y position 
text28 = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'Y:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p2_size(3)*.4 p2_size(4)*.5 30 20]);
% z position 
text29 = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'Z:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p2_size(3)*.7 p2_size(4)*.5 30 20]);

% Direction
text30 = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'X:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p2_size(3)*.1 p2_size(4)*.1 30 20]);
text31 = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'Y:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p2_size(3)*.4 p2_size(4)*.1 30 20]);
text32 = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'Z:',...
    'fontweight', 'bold',...
    'fontsize', 12,...
    'Position', [p2_size(3)*.7 p2_size(4)*.1 30 20]);

% Labels
text33 = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'EE pos',...
    'fontweight', 'bold',...
    'fontsize', 11,...
    'Position', [0 p2_size(4)*.7 100 20]);

text34 = uicontrol('parent', panel2,...
    'style', 'text',...
    'string', 'EE dir',...
    'fontweight', 'bold',...
    'fontsize', 11,...
    'Position', [0 p2_size(4)*.3 100 20]);
%% Inv Kin Panel - Edit boxes
% X pos enditable field
edit7 = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.2 p2_size(4)*.5 35 20]);
% Y pos enditable field
edit8 = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.5 p2_size(4)*.5 35 20]);
% Z pos enditable field
edit9 = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.8 p2_size(4)*.5 35 20]);

%direction
% X pos
edit10 = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.2 p2_size(4)*.1 35 20]);
% Y pos
edit11 = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.5 p2_size(4)*.1 35 20]);
% Z pos
edit12 = uicontrol('parent', panel2,...
    'style', 'edit',...
    'string', 0,...
    'position', [p2_size(3)*.8 p2_size(4)*.1 35 20]);
%% Graphical display
graph = axes('title', 'a graph',...
    'units','pixels',...
    'position', [figsize(3)*.4 figsize(4)*.1 figsize(4)*.75 figsize(4)*.75]);
    %'outerposition',[dim(3)*.125 dim(4)*.125 dim(3)*.75 dim(4)*.75]);
    
%% Options panel
r1 = uicontrol('parent', panel3,...
    'style', 'radiobutton',...
    'position', [p3_size(3)*.05 p3_size(4)*.4 15 20]);

r2 = uicontrol('parent', panel3,...
    'style', 'radiobutton',...
    'position', [p3_size(3)*.05 p3_size(4)*.1 15 20]);

text35 = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'Regular',...
    'fontweight', 'bold',...
    'fontsize', 10,...
    'Position', [p3_size(3)*.1 p3_size(4)*.4 55 17]);

text36 = uicontrol('parent', panel3,...
    'style', 'text',...
    'string', 'Demo',...
    'fontweight', 'bold',...
    'fontsize', 10,...
    'Position', [p3_size(3)*.1 p3_size(4)*.1 40 17]);

pb1 = uicontrol('parent', panel3,...
    'style', 'pushbutton',...
    'fontweight', 'bold',...
    'fontsize', 10,...
    'string', 'Home',...
    'Position', [p3_size(3)*.7 p3_size(4)*.1 60 p3_size(4)*.6]);
%% Other Stuff
    function initialize
        l0_len = 1; l1_len = l0_len/cosd(30); l2_len = l1_len; l3_len = l1_len; 
        range = [2/3*l0_len/cosd(30), 4/3*l0_len/cosd(30)];
        l1_limit = range;   % Min and Max of the acctuators
        l2_limit = range;
        l3_limit = range;
        
        set(0,'Units','pixels');
        dim = get(groot,'ScreenSize')
        fig = figure('name','Parallel Manipulator',...
            'numbertitle','off',...
            'menubar','none',...
            'units','pixels',...%);
            'outerposition',[dim(3)*.125 dim(4)*.125 800 600]);
            %'outerposition',[dim(3)*.125 dim(4)*.125 dim(3)*.75 dim(4)*.75]);
            %'position',[.1 .1 0.8 0.75]);
    end
end

